name: Crear Issue en Jira

on:
  issues:
    types:
      - opened

jobs:
  create-jira-issue:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Código
        uses: actions/checkout@v2

      - name: Crear Issue en Jira
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          curl -D- -u "gonzarliz2504:${JIRA_API_TOKEN}" -X POST -H "Content-Type: application/json" \
          --data '{
            "fields": {
              "project": {
                "key": "PP"
              },
              "summary": "Nuevo Issue desde GitHub",
              "description": "Descripción del nuevo issue creado desde GitHub",
              "issuetype": {
                "name": "Task"
              }
            }
          }' \
          "https://tu-instancia-de-jira/rest/api/2/issue/"
